### ISSUE TITLE
UI Mockups

### ISSUE THREAD

**Issue by KaustubhDhokte** [KaustubhDhokte/captionit#1]
Designing UI/UX Components

**Comment by KaustubhDhokte** [comment]
@sudhakosuri would you please put both mockup files into a directory (say uimockups) and push them? Also, try avoiding spaces into file names. (use underscores). And close this issue. Don't forget to add a commit link while you do 'close with comment'.

**Comment by sudhakosuri** [comment]
Fixed.
Commit - https://github.com/KaustubhDhokte/captionit/commit/83a4a90cf175f74403f49cc70ec1f02df3877c67
