### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by KaustubhDhokte** [KaustubhDhokte/captionit#10]
Process dataset. Cleanup and do necessary conversions.

**Comment by AtharvaMuley** [comment]
Summary: MS-COCO dataset has 82k images and each has 5 captions associated with it. So basically 410K training examples. 

Tasks:
1. Preprocessing needed, will have to normalize images before training
2. Images are in JPEG 
3. Reshape the images to 299 x 299 for input to InceptionV3 (Preprocessing main step)
4. Will need to extract features from InceptionV3's last layer and store it to the disk
5. Tokenize the captions (split it to words and create a vocabulary)
6. Pad all the sequences to be the same length as the longest one

**Comment by AtharvaMuley** [comment]
All tasks done 👍
