### ISSUE TITLE
Create Users Table

### ISSUE THREAD

**Issue by KaustubhDhokte** [KaustubhDhokte/captionit#4]
Users table creation in database. Dependant on #2 and #5

**Comment by AtharvaMuley** [comment]
I have created database named soc_database on RDS.

**Comment by KaustubhDhokte** [comment]
Table created. Commit https://github.com/KaustubhDhokte/captionit/commit/3b27dff51fdfce31d3debffe585b8cfe3611ca02
script: https://github.com/KaustubhDhokte/captionit/blob/main/src/db_scripts/tablescreate.sql
Closing this issue
